kind: Service
apiVersion: v1
metadata:
  name: service       # Zarvis ingress looking for name 'service' by default
spec:
  ports:
  - name: http
    port: 8080        # Zarvis ingress looking for port '8080' by default
    targetPort: 5000  # Flask application default port
  selector:
    app: flask-hello-world-app
